export default {
    SEARCH_CITY: 'SEARCH_CITY',
    SEARCH_CITY_SUCCESS: 'SEARCH_CITY_SUCCESS',
    SEARCH_CITY_ERROR: 'SEARCH_CITY_ERROR',
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES',
    ADD_TO_RECENT: 'ADD_TO_RECENT',
    MOVE_LOCATION: 'MOVE_LOCATION',
    SET_FAVOURITES: 'SET_FAVOURITES',
}

export const API_URL = 'http://localhost:8000/api';